apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips-api
  template:
    metadata:
      labels:
        app: trips-api
    spec:
      containers:
      - name: trips-api
        image: registryopq8736.azurecr.io/trips:1.0
        env:
          - name: SQL_USER
            value: "sqladminoPq8736"
          - name: SQL_PASSWORD
            value: "iO9tv0Hd8"
          - name: SQL_SERVER
            value: "sqlserveropq8736.database.windows.net"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8080
